config/routes.rb
Rails.application.routes.draw do
    resources :projects
    root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
    validates :title,
    presence: { message: "入力してください"},
    length: { minimum: 3, message: "短すぎ"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    
    before_action :set_project, only: [:show, :edit, :update, :destroy]
    
    def index
        @projects = Project.all
    end
    
    def show
    end
    
    def new
        @project = Project.new
    end
    
    def create
        @project = Project.new(project_params)
        if @project.save
            redirect_to projects_path
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if  @project.update(project_params)
            redirect_to projects_path
        else
            render 'edit'
        end
    end
    
    def destroy
        @project.destroy
        redirect_to projects_path
    end
    
    private 
        
        def project_params
            params[:project].permit(:title)
        end
        
        def set_project
            @project = Project.find(params[:id])
        end
        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taskapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= image_tag "logo.png" ,:size => "200x200" %>
<%= yield %>

<%= link_to "home" , projects_path %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>
    <% if @project.errors.any? %>
    <%= @project.errors.messages[:title][0] %>
    <% end %>
</p>
<p>
    <%= f.submit %>
</p>


<% end %>

app/views/projects/edit.html.erb
<h1>Edit new</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1>projects</h1>

<ul>
    <% @projects.each do | project| %>
    <li>
        <%= link_to project.title, project_path(project.id) %>
        <%= link_to "[edit]", edit_project_path(project.id) %>
        <%= link_to "[delete]",  project_path(project.id), method: :delete, data:{confirm: "are you sure"}%>
    </li>
    <% end %>
</ul>

<p><%= link_to "Add new" , new_project_path %></p>

app/views/projects/new.html.erb
<h1>Add new</h1>

<%= form_for @project do |f| %>

<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>
    <% if @project.errors.any? %>
    <%= @project.errors.messages[:title][0] %>
    <% end %>
</p>
<p>
    <%= f.submit %>
</p>


<% end %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>